getgenv().Games = {
    [15869837051] = "https://raw.githubusercontent.com/TeamUBHub/Script-Roblox/refs/heads/main/balltest_v2.lua", --Ball Test
    [82584166303511] = "https://raw.githubusercontent.com/TeamUBHub/Script-Roblox/refs/heads/main/balltest_v2.lua", --Jimmy the Normal Ball
    [11276071411] = "https://raw.githubusercontent.com/TeamUBHub/Script-Roblox/refs/heads/main/BeNPCorDie.lua", --Be NPC or Die
    [3678761576] = "https://raw.githubusercontent.com/TeamUBHub/Script-Roblox/refs/heads/main/EntrenchedV2.lua", --ENTRENCHED WW1 BETA
    [12338455185] = "https://raw.githubusercontent.com/TeamUBHub/Script-Roblox/refs/heads/main/TRT2.lua", -- Tropical Resort tycoon 2
    [16732694052] = "https://raw.githubusercontent.com/TeamUBHub/Script-Roblox/refs/heads/main/Fisch.lua", --Fisch
    [72907489978215] = "https://raw.githubusercontent.com/TeamUBHub/Script-Roblox/refs/heads/main/Fisch.lua", --Fisch Sea 2
    [70876832253163] = "https://raw.githubusercontent.com/TeamUBHub/Script-Roblox/refs/heads/main/DeadRails.lua", --Dead Rails (GAME)
    [116495829188952] = "https://gitlab.com/r_soft/main/-/raw/main/Others/deadrails.lua", --Dead Rails [APLHA]
    [2474168535] = "https://raw.githubusercontent.com/TeamUBHub/Script-Roblox/refs/heads/main/WestBound.lua", -- WestBound
    [11157166793] = "https://raw.githubusercontent.com/TeamUBHub/Script-Roblox/refs/heads/main/AntWar.lua", -- Ant War
    [3101667897] = "https://raw.githubusercontent.com/TeamUBHub/Script-Roblox/refs/heads/main/LegendsofSpeed.lua", --Legends of speed
    [14259168147] = "https://raw.githubusercontent.com/TeamUBHub/Script-Roblox/refs/heads/main/BasketballLegends.lua", --Basketball Legend
    [14386691987] = "https://raw.githubusercontent.com/TeamUBHub/Script-Roblox/refs/heads/main/BasketballLegends.lua", --Basketball Legends my park 
    [142823291] = "https://raw.githubusercontent.com/TeamUBHub/Script-Roblox/refs/heads/main/MurderMystery2.lua", --Murder Mystery 2
    [1962086868] = "https://raw.githubusercontent.com/TeamUBHub/Script-Roblox/refs/heads/main/Towerofhell.lua", --Tower of hell
    [3582763398] = "https://raw.githubusercontent.com/TeamUBHub/Script-Roblox/refs/heads/main/Towerofhell.lua", --Tower of hell pro
    [85896571713843] = "https://raw.githubusercontent.com/TeamUBHub/Script-Roblox/refs/heads/main/Bubble%20Gum%20Simulator%20INFINITY.lua", --Bubble Gum Simulator INF
    [537413528] = "https://raw.githubusercontent.com/TeamUBHub/Script-Roblox/refs/heads/main/Build%20A%20Boat%20for%20Tresure.lua", --Build a Boat For Tresure
    [122678592501168] = "https://raw.githubusercontent.com/TeamUBHub/Script-Roblox/refs/heads/main/Beaks.lua", --Beaks
    [126884695634066] = "https://raw.githubusercontent.com/TeamUBHub/Script-Roblox/refs/heads/main/Grow%20a%20Garden.lua", --grow a garden
  }
